CI: simplify linux and macOS builds
[skip ci]

diff --git a/.azure-pipelines/unix-conda-build.yml b/.azure-pipelines/unix-conda-build.yml
--- a/.azure-pipelines/unix-conda-build.yml
+++ b/.azure-pipelines/unix-conda-build.yml
@@ -30,6 +30,12 @@ steps:
 
 - script: |
     set -xe
+    cd $(Pipeline.Workspace)/modules/boost
+    git checkout 1.74
+  displayName: Select Boost 1.74
+
+- script: |
+    set -xe
     cd $(Pipeline.Workspace)/modules
     rm -fr boost
   displayName: Remove boost source on Rocky Linux 9 and Ubuntu 22.04
@@ -47,13 +53,6 @@ steps:
     git checkout dials-2.2
   displayName: Use dials-2.2 branch for Python 2
   condition: eq(variables['PYTHON_VERSION'], 'py27')
-
-- script: |
-    set -xe
-    cd $(Pipeline.Workspace)/modules/eigen
-    git checkout 3.3.9
-  displayName: Use eigen 3.3.9 for CentOS 6
-  condition: eq('${{ parameters.version[0] }}', 6)
 
 - script: |
     set -xe
@@ -149,30 +148,31 @@ steps:
     libtbx.scons -j 4
     libtbx.scons -j 4
   displayName: Configure and Build
-  condition: and(succeeded(), ne(variables['PYTHON_VERSION'], 'py310'))
+  # condition: and(succeeded(), ne(variables['PYTHON_VERSION'], 'py310'))
+  condition: succeeded()
 
-- script: |
-    set -xe
-    source $(Pipeline.Workspace)/miniforge/etc/profile.d/conda.sh
-    conda activate $(PYTHON_VERSION)
-    cd $(Pipeline.Workspace)
+# - script: |
+#     set -xe
+#     source $(Pipeline.Workspace)/miniforge/etc/profile.d/conda.sh
+#     conda activate $(PYTHON_VERSION)
+#     cd $(Pipeline.Workspace)
 
-    cd modules
-    rm -fr cbflib
-    rm -fr dxtbx
-    cd boost
-    git checkout py310
-    cd ..
-    cd ..
+#     cd modules
+#     rm -fr cbflib
+#     rm -fr dxtbx
+#     cd boost
+#     git checkout py310
+#     cd ..
+#     cd ..
 
-    python bootstrap.py build --builder=cctbxlite --use-conda=${CONDA_PREFIX} --nproc=4
-    cd build
-    source setpaths.sh
-    libtbx.configure annlib cma_es crys3d fable phenix_regression phenix_examples
-    libtbx.scons -j 4
-    libtbx.scons -j 4
-  displayName: Configure and Build
-  condition: and(succeeded(), eq(variables['PYTHON_VERSION'], 'py310'))
+#     python bootstrap.py build --builder=cctbxlite --use-conda=${CONDA_PREFIX} --nproc=4
+#     cd build
+#     source setpaths.sh
+#     libtbx.configure annlib cma_es crys3d fable phenix_regression phenix_examples
+#     libtbx.scons -j 4
+#     libtbx.scons -j 4
+#   displayName: Configure and Build
+#   condition: and(succeeded(), eq(variables['PYTHON_VERSION'], 'py310'))
 
 # test
 - script: |
@@ -205,38 +205,39 @@ steps:
       nproc=4
   failOnStderr: false
   displayName: Test
-  condition: and(succeeded(), ne(variables['PYTHON_VERSION'], 'py310'))
+  # condition: and(succeeded(), ne(variables['PYTHON_VERSION'], 'py310'))
+  condition: succeeded()
   retryCountOnTaskFailure: 3
 
-- script: |
-    set -xe
-    source $(Pipeline.Workspace)/miniforge/etc/profile.d/conda.sh
-    conda activate $(PYTHON_VERSION)
-    cd $(Pipeline.Workspace)
-    source ./build/setpaths.sh
-    rm -fr tests
-    mkdir tests
-    cd tests
-    export PYTHONDEVMODE=1
-    export PYTHONTRACEMALLOC=1
-    libtbx.run_tests_parallel \
-      module=annlib_adaptbx \
-      module=boost_adaptbx \
-      module=cctbx \
-      module=cctbx_website \
-      module=cma_es \
-      module=fable \
-      module=gltbx \
-      module=iotbx \
-      module=libtbx \
-      module=scitbx \
-      module=crys3d \
-      module=smtbx \
-      nproc=4
-  failOnStderr: false
-  displayName: Test
-  condition: and(succeeded(), eq(variables['PYTHON_VERSION'], 'py310'))
-  retryCountOnTaskFailure: 3
+# - script: |
+#     set -xe
+#     source $(Pipeline.Workspace)/miniforge/etc/profile.d/conda.sh
+#     conda activate $(PYTHON_VERSION)
+#     cd $(Pipeline.Workspace)
+#     source ./build/setpaths.sh
+#     rm -fr tests
+#     mkdir tests
+#     cd tests
+#     export PYTHONDEVMODE=1
+#     export PYTHONTRACEMALLOC=1
+#     libtbx.run_tests_parallel \
+#       module=annlib_adaptbx \
+#       module=boost_adaptbx \
+#       module=cctbx \
+#       module=cctbx_website \
+#       module=cma_es \
+#       module=fable \
+#       module=gltbx \
+#       module=iotbx \
+#       module=libtbx \
+#       module=scitbx \
+#       module=crys3d \
+#       module=smtbx \
+#       nproc=4
+#   failOnStderr: false
+#   displayName: Test
+#   condition: and(succeeded(), eq(variables['PYTHON_VERSION'], 'py310'))
+#   retryCountOnTaskFailure: 3
 
 # store tests directory as an artifact
 - script: |
